services:
  mysql_data_source:
    build: 
      context: ./mysql_db
      dockerfile: Dockerfile
    container_name: mysql_data_source
    volumes:
      - mysql_data:/var/lib/mysql
      - mysql_run:/var/run/mysqld
      - ./data_source/brazilian-ecommerce:/var/lib/data:ro
      - ./mysql_db/certs:/etc/mysql/certs:ro

    command: >
      --character-set-server=utf8mb4 
      --collation-server=utf8mb4_unicode_ci
      --authentication-policy=caching_sha2_password
    ports: 
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - de_network
    restart: unless-stopped

  postgres_dw:
    image: postgres:15
    container_name: postgres_dw
    volumes:
      - ./psql_db/scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data_source/postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - de_network

networks:
  de_network:
    driver: bridge
    name: de_network

volumes:
  mysql_run:
  mysql_data: