services:
  mysql_data_source:
    build: 
      context: ../config/database/mysql
      dockerfile: Dockerfile
    container_name: mysql_data_source
    env_file:
      - ${LOCAL_ENV}
    volumes:
      - mysql_data:/var/lib/mysql
      - mysql_run:/var/run/mysqld
      - ~/data_source/brazilian-ecommerce:/var/lib/data
      - ../config/database/mysql/certs:/etc/mysql/certs:ro
      - ../config/database/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro

    command: >
      --character-set-server=utf8mb4 
      --collation-server=utf8mb4_unicode_ci
      --default-authentication-plugin=caching_sha2_password
      --require_secure_transport=OFF
    ports: 
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - de_network
    restart: unless-stopped

  minio:
    container_name: data_lake_minio
    image: minio/minio:latest # Or a specific version, e.g., minio/minio:RELEASE.2024-09-26T00-00-00Z
    env_file:
      - ${LOCAL_ENV}
    ports:
      - "9000:9000" # S3 API port
      - "9001:9001" # MinIO Console port
    volumes:
      - minio_data:/data # Mount a named volume for persistent data storage
    command: server --console-address ":9001" /data
    networks:
      - de_network
      - kafka_network  
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 10s
      timeout: 5s
      retries: 5
    
networks:
  de_network:
    name: de_network
  kafka_network:
    name: kafka_network

volumes:
  mysql_run:
  mysql_data:
  minio_data: